### ISSUE TITLE
Not working with 7.5.2

### ISSUE THREAD

**Issue by Keksstar** [danielbuechele/atemOSC#104]
It´s no more working with ATEM 7.5.2.... Can´t downgrade due to use of the new Camera Control Panel...

**Comment by SteffeyDev** [comment]
I will upgrade and debug, I don't see any changes in the SDK so not sure what changed

**Comment by Keksstar** [comment]
Any success so far?

**Comment by SteffeyDev** [comment]
Apologies, I let this fall aside but have just added it to my calendar for my next testing availability on Sunday, so will hopefully be able to then

**Comment by SteffeyDev** [comment]
Ok, I just updated my ATEM Studio 4K to 7.5.2 and AtemOSC is working exactly the same as before for me... Can you provide details like model of switcher?

**Comment by nmalexandersen** [comment]
I can confirm that there is an issue with 7.5.2. I am using Television Studio Pro 4k
The ATEM OSCX app has a green light, but states that you need to connect to the mixer when you try to enter the help/commandlist page. Using 7.5.2, Macbook Pro, Latest Mac OS

**Comment by SteffeyDev** [comment]
Are you connecting over ethernet or wifi?

**Comment by nmalexandersen** [comment]
Hello Daniel. I an using Ethernet. 192.168.1.xxx range. Tested with several different cables, but the same result. Both the Mac machine and the ATEM switcher was able to communicate over the network just fine during testing.

Sendt fra min iPhone

27. mar. 2019 kl. 15:27 skrev Peter Steffey <notifications@github.com<mailto:notifications@github.com>>:


Are you connecting over ethernet or wifi?

O—

**Comment by SteffeyDev** [comment]
Assumed fix, this is an old version so not relevant anymore
