### ISSUE TITLE
Need help please! "new midi template from selection" not working

### ISSUE THREAD

**Issue by zmania007** [danielbuechele/atemOSC#109]
I can't seem to get past the first few steps of setting my atem w/ the x touch mini. For example, I followed the steps to create the Cam 1 Program label but it won't show up in the "message" window. I pressed the first top button on the x touch mini controller, and in OSCulatar I hovered over the "on" midi note in the "monitor" window, selected "new midi template from selection," and followed the naming convention on my bmd switcher. Despite all this, I don't see Cam 1 Program as a unique midi event in the "message" window, all I see is the same midi events (even pressing different buttons I see the same midi events):

/midi/cc9/11
/midi/note/11
      0: patch
      1: velocity
      2: trigger﻿

Please help

**Comment by SteffeyDev** [comment]
Are you having an issue with atemOSC or only with OSCulator?  atemOSC doesn't have a "new midi template from selection" feature.

**Comment by zmania007** [comment]
I apologize for the confusion. Yes, this issue comes up in OSCulator.

**Comment by randallpacker** [comment]
For all of you having difficulty using midi messages to control atemOSC, I would recommend using Cycling 74 Max MSP which really simplifies the process of translating midi to OSC, and there is a Max patch example on this Git Hub site. 

That said, I wanted to take a moment to thank Daniel for his superb software! I have been using it for several years without any issues at all, with both an ATEM Television Switcher and ATEM Television HD.  

Bravo Daniel!!!! Please keep it alive for those of us who depend on it for our work.

**Comment by SteffeyDev** [comment]
If you need help with OSCulator, your best bet is to post on their forum: https://osculator.net/forum/

**Comment by zmania007** [comment]
Thanks SteffeyDev, I appreciate it
