### ISSUE TITLE
Send OSC from AppleScript?

### ISSUE THREAD

**Issue by zackhinrichs** [danielbuechele/atemOSC#115]
Hello! was curious if anyone knew of a way to send OSC messages via applescript to ATEM OSC? What I’m aiming for is to have my PTZ camera control software only call up the position presets via http request IF the atem software control is showing that camera as NOT being on Program output, to avoid jerking between presets on the Live program output. I hope to do this through a conditional if / then type statement through applescript triggered by my midi touchscreen software, XOTOPAD. any help or pointing me in the right direction would be greatly appreciated!

**Comment by danielbuechele** [comment]
Yes, this is possible. I am using this in some setups. Basically, what I am doing, is using AppleScript to execute shell commands. There are a bunch of different tools out there, to send OSC messages from the command line. Not tested, but this could be something that helps you: https://github.com/russellmcc/oscurl

**Comment by zackhinrichs** [comment]
Wow! Thanks for the fast response Daniel!

I’ll have to get that a try!!

-Zack

**Comment by zackhinrichs** [comment]
Hi Daniel!

So I tried to install the node.js and run the command that you suggested
from russellmcc/oscurl. I'm getting this error message in terminal

Would you possibly be able to post an example of how you've used
applescript to send osc messages with shell command? Are you using that
oscurl tool yourself to do this?

Currently, i'm trying to install a different osc command line tool called
sendosc by yoggy and have not been successful yet.

Thanks for your help!

-Zack

**Comment by sneat** [comment]
@zackhinrichs I've used [sendosc](https://github.com/yoggy/sendosc) before successfully, I'll try to dig up the applescript file.

**Comment by sneat** [comment]
Turns out it was the samples directory all along @zackhinrichs https://github.com/danielbuechele/atemOSC/blob/master/samples/controllermate-actionscript.txt

**Comment by SteffeyDev** [comment]
I updated the readme to make this information easier to find for new people (hopefully)
