### ISSUE TITLE
SysEx messages

### ISSUE THREAD

**Issue by Jingjing19940227** [danielbuechele/atemOSC#116]
Having trouble with OSCulator and atemOSC now.
My MIDI keyboard slider only send SysEx messages to OSCulator now. By checking the log I found all the messages like F0 7F 7F 04 01 00 00 F7. The second [00] changes when I slide the slider. Is there any possibility to convert these messages to normal messages and control the BMD ATEM slider?
Thank you!

**Comment by SteffeyDev** [comment]
@Jingjing19940227  Have you been able to figure out your issue in the past few months, or do you still need help?

**Comment by SteffeyDev** [comment]
Assumed fixed, lack of user response
