### ISSUE TITLE
ATEM AUX problem. 

### ISSUE THREAD

**Issue by tomcie** [danielbuechele/atemOSC#117]
I'm not programmer. I'm testing your great app to ATEM control. It is excelent idea. I have problem With control AUXs output. My set is:
ipad osctouch - mac pro with atemOSC and osceditor. My ATEM 4k 2 ME is 7.4. 
I can control all AUX but always it switchs only to input 1. My command is:
/atem/aux/5 2          // it switch AUX5 for input 1
/atem/aux/1 3          // it switch AUX1 for input 1    etc.

I tried to find something about it in FAQ but with no succes. Could you help?

**Comment by tomcie** [comment]
How to make flat value? I use only touch efitor. I try put 5.0 instead 5 - no sucess. Coul you write me short example?

**Comment by SteffeyDev** [comment]
5.0 is float, that's what I would have tried.  Can you get the logs from the atemOSC help menu and post them here?

**Comment by tomcie** [comment]
Sure
[2019-01-25 15:46:00] Received OSC message: /atem/aux/1 5.0 	Value: <OSCVal f 1.000000>
[2019-01-25 15:46:01] Received OSC message: /atem/aux/1 6.0	Value: <OSCVal f 1.000000>
[2019-01-25 15:46:03] Received OSC message: /atem/aux/1 5.0 	Value: <OSCVal f 1.000000>
[2019-01-25 15:46:04] Received OSC message: /atem/aux/1 6.0	Value: <OSCVal f 1.000000>

**Comment by tomcie** [comment]
I tried to change AUX 1 to 5 and 6 2 times

**Comment by SteffeyDev** [comment]
Ah I see the issue.  Do you see it? You are sending the address “/atem/aux/1 6.0” with the value “1.00”, where you should be sending the address “/atem/aux/1” with a value of “6.00”.  Are you using TouchOSC?

**Comment by tomcie** [comment]
Yes. Touch OSC on ipad

**Comment by tomcie** [comment]
Program and preview work fine, transition too.

**Comment by SteffeyDev** [comment]
Ok, download the Advanced Video Control TouchOSC file located here: https://github.com/danielbuechele/atemOSC/tree/master/samples

The AUX control in this template works, so just make yours look identical and it should work for you too

**Comment by guitarzan2** [comment]
I am using atemOSC along with Osculator to control an ATEM TVS HD (1 ME). When trying to program the aux input source, I always reverts to black. Ex: /atem/aux/1 4 is what I'm putting in to the atemosc, 4 being an active video source.  B ut the aux will only show black. Any advice?  Your system is fantastic, by the way. Thank you!

**Comment by sneat** [comment]
@guitarzan2 what do the logs from the atemOSC help menu show? It sounds like you're sending the message to the address `/atem/aux/1 4` with a value of `0`, rather than sending a message to the address `/atem/aux/1` with a value of `4`.

**Comment by guitarzan2** [comment]
[2019-04-04 19:08:57] Received OSC message: /atem/aux/1 4	Value: (null)

**Comment by guitarzan2** [comment]
<img width="434" alt="Screen Shot 2019-04-04 at 7 12 37 PM" src="https://user-images.githubusercontent.com/49293881/55596346-a7a04280-570d-11e9-99f2-1241749db620.png">

**Comment by sneat** [comment]
You'll need to adjust the arguments so that you are sending a value of `4` to the address `/atem/aux/1`. Currently the atemOSC logs are showing that you are sending the whole thing to the address without a value (showing as `null`).

**Comment by guitarzan2** [comment]
Okay. Still not working.

LOG:
[2019-04-04 21:11:58] Received OSC message: /atem/aux/1	Value: <OSCVal i 1>
[2019-04-04 21:11:58] Received OSC message: /atem/aux/1	Value: <OSCVal i 0>

Here's how I changed the argument.
<img width="435" alt="4" src="https://user-images.githubusercontent.com/49293881/55599683-7bd98880-571e-11e9-8ef7-3c4fed392536.png">

I'm not giving up...

**Comment by guitarzan2** [comment]
SOLVED. Simply put the source number in a pair pf parentheses.
<img width="431" alt="solved" src="https://user-images.githubusercontent.com/49293881/55599878-63b63900-571f-11e9-8471-711623c6a16a.png">

**Comment by sneat** [comment]
I believe (I haven't really used OSCulator much) that your `arg[4]` before should actually be `arg[1]` being the 1st argument in the message. But glad you got it solved.
