### ISSUE TITLE
ATEM Television Studio Pro 4K connection not working properly, feedback missing

### ISSUE THREAD

**Issue by Kalevi12** [danielbuechele/atemOSC#119]
Hello, Atem osc can not find osc addresses from ATEM Television Studio Pro 4K. I mean those from help menu. It says " Switcher needs to be connected to show OSC addresses". There is green mark after switcher  name so it has been recognised and I can get midi controller to work some how (but Bar function does not work properly). It seems that Atem osc and Oscillator won't get feedback from atem).  Can it be osc out ip address which is missing (what it should be - I have tried 127.0.0.1) or incoming/outgoin port ( now 9000 and 8000). Osc suggest 4444 and 3333 at startup but osculator won't work with those. Any ideas?

**Comment by SteffeyDev** [comment]
Hm, not sure why it wouldn't show addresses if it is connected, might be a bug.  I can test it out sometime.  the OSC out IP address is where to send feedback to, for OSCulator the OSC out address should be 127.0.0.1:8000.  Then OSCulator should be set up to send OSC messages to 127.0.0.1:3333.  If you still have issues, screenshots would help

**Comment by SteffeyDev** [comment]
Hopefully the feedback is working, closing this in favor of #104 for the help menu issues.
