### ISSUE TITLE
Support for ATEM Software 8.0.2

### ISSUE THREAD

**Issue by jrmilt** [danielbuechele/atemOSC#125]
Hey @danielbuechele ! Firstly I want to thank you for this software and how it makes my workflow easy with the Novation Launchpad and Osculator to control the TVS HD.

I was wondering if there will be any upcoming support for the latest ATEM Software 8.0.2? I blindly updated the firmware on my switcher the other day and broke my link to atemosc which I was pretty bummed that I made that mistake. I tried to downgrade the switcher to the last supported firmware and couldn’t :( 

I thank you in advance if this is possible to update.

**Comment by bevanjkay** [comment]
Hi @danielbuechele, ATEM Software 8.1 is released now, and is required to run Mac OS 10.15 (Catalina). Is there any update expected soon that will regain compatibility?

**Comment by randallpacker** [comment]
I just checked the Blackmagic Website and it says that version 8.1 is also compatible with Mojave. However I would also like to know if the current atemOSC will work with this new version.

**Comment by bevanjkay** [comment]
@randallpacker I tested it yesterday and it wasn't working. I had to rollback ATEM to 7.4, which means I can't run ATEM Software Control on our Mac Mini, because it is running Catalina.

**Comment by randallpacker** [comment]
Good to know. Thanks.

**Comment by SteffeyDev** [comment]
I'll see if I can get a compatible version ready for you guys to test.

**Comment by randallpacker** [comment]
Thanks Peter!

**Comment by SteffeyDev** [comment]
Ok @randallpacker @bevanjkay If you guys can test, just download the zip of the repository and try out the version of atemOSC.app included.  No clue if it will run.  If it does run, just ignore the popup about a newer version, this is an unofficial pre-release version.  Let me know if it works or not.  I haven't fully updated the documentation yet and there's probably a few bugs, but maybe it can be a stopgap for now

**Comment by randallpacker** [comment]
I'm still waiting to update to Catalina and I am using ATEM software 7.5.4 with no problem, so I think I'll wait until you have a stable version, unless you need people to test.

**Comment by SteffeyDev** [comment]
I may be able to test in a few weeks after the holidays, I’m hoping this will work for those who need it until then

**Comment by bevanjkay** [comment]
Thanks Peter. I’ll check it out during the week and get back to you.

**Comment by jrmilt** [comment]
I’ll test it out in the next day or two :)

**Comment by carbon43** [comment]
I can probably test as well some time in the next week. New laptop came with Catalina, so yeah... >_< buggiest MacOS release since the 10.0 beta imo. Thank you Peter!

**Comment by bevanjkay** [comment]
I can confirm that it is working with ATEM 8.1. Thanks!

**Comment by SteffeyDev** [comment]
Oh good to hear! Would you be interesting in testing all the main features @bevanjkay to make sure all the core commands (preview, program, transition, DSK, USK) are working on this version? If you give me the OK, I can officially release. Otherwise it will be a few weeks.

**Comment by bevanjkay** [comment]
@SteffeyDev I have tested setting preview, program, runnings macros, transitions, toggling DSK and USK, and setting a different fill source for USK. All seems to be working as expected.

**Comment by SteffeyDev** [comment]
Great to hear!  I'll push this update as official now then and then probably release another version next week after more testing if I find any issues
