### ISSUE TITLE
ATEM OSC Fade to Black Rate

### ISSUE THREAD

**Issue by guillaumec1** [danielbuechele/atemOSC#126]
Hi Daniel,

I am using Atemosc to control our Atem with Qlab.
It's great thanks.
Now I wanted to use the FTB transition but each time with a different rate.
Is there a way to do this?
We could not find the command in the API list. (found (/atem/FTBRate FRAMES)  for another soft: ofAtem but it seems that it doesn't work with atemosc.)

thank you in advance for your help.

Guillaume

**Comment by sneat** [comment]
@guillaumec1 if you only have a few rates that you want to switch between, you could make use of [macros](https://github.com/danielbuechele/atemOSC#macros) to do the setting of the rate prior to calling the FTB transition.

E.g. lets say you were wanting to switch between a rate of 1sec and 2sec, you could create two macros through the ATEM Software Control Panel and then call:
```
/atem/macros/0/run
/atem/transition/ftb

/atem/macros/1/run
/atem/transition/ftb
```

**Comment by guillaumec1** [comment]
Thanks,

I did not know about macros, and that s a great tool.
I made macro containing rate and FTB in once. It s perfect for my need-

Have a great day,

Guillaume
