### ISSUE TITLE
DSK Auto not working?

### ISSUE THREAD

**Issue by randallpacker** [danielbuechele/atemOSC#129]
I haven't used DSK Auto for awhile, but just noticed it does not seem to be working. When the command: /atem/dsk/1/on-air/auto is sent, the On Air and Auto buttons blink momentarily on and off.  I am using ATEM Software Control 7.5.2, atemOSC 2.5.6, ATEM Television Studio HD. It was working perfectly previously, the only change in my setup is I upgraded from 7.5.1 to 7.5.2 several weeks ago. Could that be the problem? Thanks!

**Comment by SteffeyDev** [comment]
are you sending the commands from MIDI or from an OSC controller? Make sure you are sending only /atem/SDK/1/on-air/auto with a float value of 1, and are not also sending 0 to the same command shortly thereafter (which would cause the blinking behavior you are describing).

**Comment by randallpacker** [comment]
False alarm, sorry! I am using Max/MSP to send OSC messages to atemOSC and I had mistakenly had two patches open which were conflicting with one another. All is good! Thanks!!
