### ISSUE TITLE
add DSK fill and key sources

### ISSUE THREAD

**Issue by jgastonraoul** [danielbuechele/atemOSC#130]
Hi.

It would be nice to add DSK key and fill sources endpoints as in USK.

Regards,
Jérémie

**Comment by randallpacker** [comment]
Agreed! DSK key and fill sources as well as DSK clip and gain levels. These are all implemented in USK but not DSK.

**Comment by SteffeyDev** [comment]
@jgastonraoul @randallpacker Implemented in 3.0.0, try it out and let me know what you think!
