### ISSUE TITLE
 Support for ATEM Software 8.0.3

### ISSUE THREAD

**Issue by zackdickinson16** [danielbuechele/atemOSC#131]
Hi I'm trying to use my ATEM Television Studio Pro 4K running 8.0.3 with atemOSC. it will connect to the software but when I go into the help menu and look for OSC addresses it tells me "Switcher needs to be connected to show OSC addresses". And when I go into log is says "Cannot process command /atem/led/red because no switcher connected"

Will there be a new release that works with switchers running 8.0.3?.

ATEM Television Studio Pro 4K
ATEM Software Control 8.0.3
atemOSC - Version v2.5.6

**Comment by SteffeyDev** [comment]
We’re skipping straight to 8.1 support, should be released soon. Trial version is available now (see #125)

**Comment by SteffeyDev** [comment]
Ok, just released 2.5.7 with support for 8.1
