### ISSUE TITLE
3.0 and 2.5.7 crashing on Mojave

### ISSUE THREAD

**Issue by mogzealio** [danielbuechele/atemOSC#138]
atemOSC 3.0 and 2.5.7 are crashing consistently for me on 3.0 and 2.5.7. Just got an Atem Mini and am dying to try OSC control with Qlab. Happy to help with testing. Crash report:

`Process:               atemOSC [1116]
Path:                  /Applications/atemOSC.app/Contents/MacOS/atemOSC
Identifier:            cc.buechele.atemOSC
Version:               2.5.7 (1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           atemOSC [1116]
User ID:               501

Date/Time:             2020-02-12 17:03:51.761 +0000
OS Version:            Mac OS X 10.14.6 (18G103)
Report Version:        12
Anonymous UUID:        764CB514-6E20-5474-C97D-A71A6AC67C49

Time Awake Since Boot: 23000 seconds

System Integrity Protection: enabled

Crashed Thread:        2  Dispatch queue: com.apple.root.default-qos

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000000000000271a
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [1116]

VM Regions Near 0x271a:
--> 
    __TEXT                 000000010b5ad000-000000010b5ce000 [  132K] r-x/rwx SM=COW  /Applications/atemOSC.app/Contents/MacOS/atemOSC

Thread 0:: Dispatch queue: com.apple.main-thread
0   com.apple.AppKit              	0x00007fff420cc15a -[NSView(NSViewControllerSupport) _viewController] + 0
1   com.apple.AppKit              	0x00007fff4222a971 -[NSView _recursiveViewWillAppearBecauseUnhidden] + 50
2   com.apple.AppKit              	0x00007fff420de2f9 -[NSView(NSInternal) _setHidden:setNeedsDisplay:] + 307
3   cc.buechele.atemOSC           	0x000000010b5aea55 __40-[SettingsWindow showSwitcherConnected:]_block_invoke + 93
4   libdispatch.dylib             	0x00007fff709a45f8 _dispatch_call_block_and_release + 12
5   libdispatch.dylib             	0x00007fff709a563d _dispatch_client_callout + 8
6   libdispatch.dylib             	0x00007fff709b068d _dispatch_main_queue_callback_4CF + 1135
7   com.apple.CoreFoundation      	0x00007fff44a73a37 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
8   com.apple.CoreFoundation      	0x00007fff44a73161 __CFRunLoopRun + 2289
9   com.apple.CoreFoundation      	0x00007fff44a7261e CFRunLoopRunSpecific + 455
10  com.apple.HIToolbox           	0x00007fff43cd11ab RunCurrentEventLoopInMode + 292
11  com.apple.HIToolbox           	0x00007fff43cd0ee5 ReceiveNextEventCommon + 603
12  com.apple.HIToolbox           	0x00007fff43cd0c76 _BlockUntilNextEventMatchingListInModeWithFilter + 64
13  com.apple.AppKit              	0x00007fff4206977d _DPSNextEvent + 1135
14  com.apple.AppKit              	0x00007fff4206846b -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1361
15  com.apple.AppKit              	0x00007fff42062588 -[NSApplication run] + 699
16  com.apple.AppKit              	0x00007fff42051ac8 NSApplicationMain + 777
17  libdyld.dylib                 	0x00007fff709f23d5 start + 1

Thread 1:
0   libsystem_pthread.dylib       	0x00007fff70be53f0 start_wqthread + 0

Thread 2 Crashed:: Dispatch queue: com.apple.root.default-qos
0   cc.buechele.atemOSC           	0x000000010b5b75cf -[AppDelegate switcherConnected] + 1570
1   cc.buechele.atemOSC           	0x000000010b5b6dda __25-[AppDelegate connectBMD]_block_invoke_2 + 73
2   libdispatch.dylib             	0x00007fff709a45f8 _dispatch_call_block_and_release + 12
3   libdispatch.dylib             	0x00007fff709a563d _dispatch_client_callout + 8
4   libdispatch.dylib             	0x00007fff709a7a53 _dispatch_queue_override_invoke + 763
5   libdispatch.dylib             	0x00007fff709b33bc _dispatch_root_queue_drain + 324
6   libdispatch.dylib             	0x00007fff709b3b46 _dispatch_worker_thread2 + 90
7   libsystem_pthread.dylib       	0x00007fff70be56b3 _pthread_wqthread + 583
8   libsystem_pthread.dylib       	0x00007fff70be53fd start_wqthread + 13

Thread 3:
0   libsystem_pthread.dylib       	0x00007fff70be53f0 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	0x00007fff70be53f0 start_wqthread + 0

Thread 5:: com.apple.CFSocket.private
0   libsystem_kernel.dylib        	0x00007fff70b2e61a __select + 10
1   com.apple.CoreFoundation      	0x00007fff44aa12d2 __CFSocketManager + 635
2   libsystem_pthread.dylib       	0x00007fff70be62eb _pthread_body + 126
3   libsystem_pthread.dylib       	0x00007fff70be9249 _pthread_start + 66
4   libsystem_pthread.dylib       	0x00007fff70be540d thread_start + 13

Thread 6:
0   libsystem_kernel.dylib        	0x00007fff70b2e61a __select + 10
1   com.vidvox.VVOSC              	0x000000010b608394 -[OSCInPort OSCThreadProc] + 388
2   com.apple.Foundation          	0x00007fff46ccd112 __NSThread__start__ + 1194
3   libsystem_pthread.dylib       	0x00007fff70be62eb _pthread_body + 126
4   libsystem_pthread.dylib       	0x00007fff70be9249 _pthread_start + 66
5   libsystem_pthread.dylib       	0x00007fff70be540d thread_start + 13

Thread 7:
0   libsystem_pthread.dylib       	0x00007fff70be53f0 start_wqthread + 0

Thread 8:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff70b2722a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff70b2776c mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff44a7394e __CFRunLoopServiceMachPort + 328
3   com.apple.CoreFoundation      	0x00007fff44a72ebc __CFRunLoopRun + 1612
4   com.apple.CoreFoundation      	0x00007fff44a7261e CFRunLoopRunSpecific + 455
5   com.apple.AppKit              	0x00007fff420714a2 _NSEventThread + 175
6   libsystem_pthread.dylib       	0x00007fff70be62eb _pthread_body + 126
7   libsystem_pthread.dylib       	0x00007fff70be9249 _pthread_start + 66
8   libsystem_pthread.dylib       	0x00007fff70be540d thread_start + 13

Thread 9:
0   libsystem_kernel.dylib        	0x00007fff70b2a86a __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff70be956e _pthread_cond_wait + 722
2   com.blackmagic-design.switchers.api	0x0000000110867acc TransferQueue::TransferThread() + 444
3   com.blackmagic-design.switchers.api	0x0000000110866f19 TransferQueue::TransferThreadFunc(void*) + 9
4   libsystem_pthread.dylib       	0x00007fff70be62eb _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff70be9249 _pthread_start + 66
6   libsystem_pthread.dylib       	0x00007fff70be540d thread_start + 13

Thread 10:
0   libsystem_kernel.dylib        	0x00007fff70b2a86a __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff70be956e _pthread_cond_wait + 722
2   com.blackmagic-design.switchers.api	0x00000001107d6908 AtomDispatch::DispatchThread() + 88
3   com.blackmagic-design.switchers.api	0x00000001107d6779 AtomDispatch::DispatchThreadFunc(void*) + 9
4   libsystem_pthread.dylib       	0x00007fff70be62eb _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff70be9249 _pthread_start + 66
6   libsystem_pthread.dylib       	0x00007fff70be540d thread_start + 13

Thread 11:
0   libsystem_kernel.dylib        	0x00007fff70b2a86a __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff70be956e _pthread_cond_wait + 722
2   com.blackmagic-design.switchers.api	0x00000001107d7f08 CBMDSwitcher::DeleteLaterThreadFunc(void*) + 40
3   libsystem_pthread.dylib       	0x00007fff70be62eb _pthread_body + 126
4   libsystem_pthread.dylib       	0x00007fff70be9249 _pthread_start + 66
5   libsystem_pthread.dylib       	0x00007fff70be540d thread_start + 13

Thread 12:
0   libsystem_kernel.dylib        	0x00007fff70b2722a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff70b2776c mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff44a7394e __CFRunLoopServiceMachPort + 328
3   com.apple.CoreFoundation      	0x00007fff44a72ebc __CFRunLoopRun + 1612
4   com.apple.CoreFoundation      	0x00007fff44a7261e CFRunLoopRunSpecific + 455
5   com.apple.CoreFoundation      	0x00007fff44a72432 CFRunLoopRun + 40
6   com.blackmagic-design.switchers.api	0x00000001107d6539 USBCFRunLoop::runThread() + 153
7   com.blackmagic-design.switchers.api	0x00000001107d662d void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, USBCFRunLoop::startThread()::$_0> >(void*) + 45
8   libsystem_pthread.dylib       	0x00007fff70be62eb _pthread_body + 126
9   libsystem_pthread.dylib       	0x00007fff70be9249 _pthread_start + 66
10  libsystem_pthread.dylib       	0x00007fff70be540d thread_start + 13

Thread 13:
0   libsystem_kernel.dylib        	0x00007fff70b2e61a __select + 10
1   com.blackmagic-design.switchers.api	0x00000001107f55da BMDSwitcherConnection::ConnectionThread() + 522
2   com.blackmagic-design.switchers.api	0x00000001107f5359 BMDSwitcherConnection::ConnectionThreadFunc(void*) + 9
3   libsystem_pthread.dylib       	0x00007fff70be62eb _pthread_body + 126
4   libsystem_pthread.dylib       	0x00007fff70be9249 _pthread_start + 66
5   libsystem_pthread.dylib       	0x00007fff70be540d thread_start + 13

Thread 2 crashed with X86 Thread State (64-bit):
  rax: 0x0000000080000004  rbx: 0x00000000000000f8  rcx: 0x000070000cbc4da0  rdx: 0x0000000000000000
  rdi: 0x000000000000271a  rsi: 0x9446e36a26806507  rbp: 0x000070000cbc4e10  rsp: 0x000070000cbc4d00
   r8: 0x00008b74631d57a0   r9: 0xffffffff00000000  r10: 0x00007fca85842360  r11: 0x0000000000000040
  r12: 0x00007fca83f07268  r13: 0x0000000000000040  r14: 0x00007fca83f07160  r15: 0x000070000cbc4dd0
  rip: 0x000000010b5b75cf  rfl: 0x0000000000010206  cr2: 0x000000000000271a
  
Logical CPU:     2
Error Code:      0x00000004
Trap Number:     14`

**Comment by mogzealio** [comment]
Small update - atemOSC 2.5.7 seems to stay running sometimes if the network cable between Mac and Atem is unplugged. It then crashes once I reconnect the network cable.

**Comment by SteffeyDev** [comment]
@mogzealio  Please download and run this version, then send the crash log you get.  This will allow me to debug and find the issue.

[atemOSC.zip](https://github.com/danielbuechele/atemOSC/files/4239698/atemOSC.zip)

**Comment by SteffeyDev** [comment]
@mogzealio Please try latest version 3.0.1, and post crash log if it continues to crash.

**Comment by mogzealio** [comment]
works like a charm (on 10.14.6) - thank you! I very much appreciate this tool.
