### ISSUE TITLE
SDK 6.4

### ISSUE THREAD

**Issue by bejohnny** [danielbuechele/atemOSC#14]
Hi 

Please consider updated atemOSC to more recent BMD SDK 6.4 support -- The software is extremely useful, but needs to keep up with the SDK or it breaks.. Especially now the SDK includes macro controls support :)

Thanks!

johnny deKam

**Comment by sneat** [comment]
@bejohnny I've updated the version to 6.4 in our repository at https://github.com/LanSmash/atemOSC

I don't have an ATEM running that version to test against, so give it a go please and let me know if you have any troubles.

**Comment by sneat** [comment]
@bejohnny FYI Macro support has been added in the LanSmash fork.

**Comment by SteffeyDev** [comment]
Closing because OBE, now on 7.2
