### ISSUE TITLE
Atem Mini support

### ISSUE THREAD

**Issue by saprolido** [danielbuechele/atemOSC#144]
Hi there. First of all I thank you for your soft is incredible and very useful. I used it at school and I wanted to try it on a small setup at home. I'm using the atem mini but every time I try to run it I have the message: "Could not get IBMDSwitcherAudioMixer interface".

I don't really know what I'm doing wrong, because I'm mainly on the sound area. I manage to connect to the switcher and the atemOSC recognizes it as ATEM Mini, but that's as far as I go.

I hope that you can help me, have a good one!
![Screen Shot 2020-03-03 at 6 10 15 PM](https://user-images.githubusercontent.com/6265793/75831844-3e400e00-5d7a-11ea-9a7f-440bda184411.png)

**Comment by SteffeyDev** [comment]
What version are you using?

**Comment by SteffeyDev** [comment]
It might be best to try 2.5.7 if you are trying 3.0.0 and its not working. 3.0.0 has a few known bugs that we are working on fixing.

**Comment by saprolido** [comment]
I'll try it!!! Thank u so much!

**Comment by saprolido** [comment]
Just Tested it.... well. stopped crashing but... I just can't get the atem OSC to connect to my atem mini.... this happens all the time: 

![Screen Shot 2020-03-03 at 21 15 32](https://user-images.githubusercontent.com/6265793/75841761-24132980-5d94-11ea-8166-67e793ed35e4.png)

It starts, gets the switcher name, and after that "[2020-03-03 21:15:21] Could not get IBMDSwitcherAudioMixer interface"

I don't know If I'm doing something wrong... BTW I tried on mavericks, high sierra and mojave with version 3.0.3, 3.0.2, 3.0.1, 3.0, 2.5.7, and 2.5.6. Also tried with usb/network, usb solo and network solo...

Thanks for the reply and for your time

**Comment by sneat** [comment]
@SteffeyDev do you happen to know if anyone has successfully connected to an ATEM Mini before? Do they actually support the audio mixer interface? It reads like it should: https://www.blackmagicdesign.com/au/products/atemmini

**Comment by Julusian** [comment]
The mini uses fairlight audio instead of the classic audio stuff.
This is a different set of interfaces in the api.
The constellation and I think some of the tv studio pro range also use fairlight

**Comment by Fechtenburg** [comment]
I have the same  "Could not get IBMDSwitcherAudioMixer interface".  issue with version 3.0.1

If I try version 3.0.3 the App. window shows up shortly, and then closes down.

I have a MacBook Pro (15-inch, 2017) running  macOS Catalina

**Comment by AndreasMUC** [comment]
Same here. 3.0.3 and 3.0.2 immediately crash (OSX 10.15.4). 
3.0.1 is not crashing but ATEM Mini is not working due to the audio implementation mentioned above.

**Comment by SteffeyDev** [comment]
@AndreasMUC, @Fechtenburg, @saprolido please try 3.0.4 and let me know if it fixes the crash issue

**Comment by AndreasMUC** [comment]
:) The issue is fixed. Thank you!!

**Comment by Fechtenburg** [comment]
Fixed, ATEM Mini, macOS Catalina 10.15.4 ;0)

**Comment by SteffeyDev** [comment]
Awesome to hear, finally
