### ISSUE TITLE
Successful test of v 3.0

### ISSUE THREAD

**Issue by randallpacker** [danielbuechele/atemOSC#145]
I just wanted to let everyone know that I ran a test of all the atemosc functions with v3.0 and everything is working perfectly. I am using ATEM software 8.1 with an ATEM HD switcher. I'm running the latest version of Mojave. I have two Hyperdeck Studios and one Hyperdeck Mini. 

I know this is not the most recent version (because I am in the middle of production) but just wanted to say that v3.0 seems to be entirely stable with Mojave, at least with my setup. For those having problems, I recommend reverting to this version.

Thanks for all the great development work!!

**Comment by dombuerkler** [comment]
Hi randallpacker

I'm absolutely new to this stuff. We got some nice ATEM toys and i wanna be able to control our 4ME Broadcast Studio 4K with OSC. Everytime i try to setup atemOSC, i get to a point where i don't know what to fill in. May you can help me?

atemOSC: 3.0.1
Switcher Studio 4K: 8.1.2
Switcher IP Address: 192.168.2.100
macOS High Sierra
mac IP Address: 192.168.2.220

Now the parameters from atemOSC:
Switcher IP Adress: 192.168.2.100
Switcher Name: *generated automatic*
OSC Out IP Adress: *I've no idea what to fill in here! My macs IP Address?*
OSC incoming port: *set from atemOSC to 4444*
outgoing: *set from atemOSC to 3333*

I'm not able to send OSC commands to the ATEM Switcher (via QLab). The log from atemOSC is empty.

I'm looking forward reading from you.

Cheers
dobu

**Comment by danielbuechele** [comment]
Hey Dobu,
when running the software that is sending the OSC messages is running on the same computer as atemOSC, the OSC output address should be `127.0.0.1` (which is localhost). Outgoing and incoming ports can be left to the defaults, just make sure to set the ports accordingly in Qlab.

**Comment by dombuerkler** [comment]
Hey Daniel
Perfect, that was my mistake! Now everything works as fine as it should. Thank you for you little application! :)

**Comment by SteffeyDev** [comment]
@randallpacker closing this issue as 3.0.5 is now released and stable, don't want to confuse anyone. 3.0.1-3.0.3 crashed so this was useful, but now that is fixed :)
