### ISSUE TITLE
atem production studio 4k does not connect properly or crashes OSC

### ISSUE THREAD

**Issue by zackdickinson16** [danielbuechele/atemOSC#148]
When connecting atem production studio 4k to OSC v3.0.1 it shows "could not get IBMDSwircherAudioMixer Interface".  OSC v3.0.1 is the only version that works, Crashes in any other version.

atem production studio 4k
ATEM Switchers 8.2 also tried 8.1
OSC v3.0.1
![Screen Shot 2020-04-11 at 8 38 59 PM](https://user-images.githubusercontent.com/57646814/79057301-52f3a980-7c36-11ea-9d38-4a2b10c777fb.png)
![Screen Shot 2020-04-11 at 8 39 51 PM](https://user-images.githubusercontent.com/57646814/79057303-571fc700-7c36-11ea-98a4-f3d1937e8c27.png)

**Comment by zackdickinson16** [comment]
Disclaimer: I don't know what I'm doing

**ATEM Production Studio 4k
ATEM Switchers 8.1.1
OSC v3.0.3**

**I was looking through the "atemOSC.xcodeproj" file of OSC v3.0.3 and when I "built" the file
connected to my switcher it crashed showing me this:**

![Screen Shot 2020-04-11 at 11 46 29 PM](https://user-images.githubusercontent.com/57646814/79059408-074df980-7c50-11ea-93a3-eb09c8b03fbf.png)

**I went ahead and deleted the code selected. shown here:**

![Screen Shot 2020-04-12 at 12 00 39 AM](https://user-images.githubusercontent.com/57646814/79059467-bc80b180-7c50-11ea-8f3c-4709765c28d8.png)

**I tried building the file again and I connected without crashing and it seems to work fine with my ATEM Production Studio 4k. I don't know what I messed up by deleting this but it works for what I'm trying to do.**

![Screen Shot 2020-04-12 at 12 05 31 AM](https://user-images.githubusercontent.com/57646814/79059528-75df8700-7c51-11ea-86d6-a313c6054ee6.png)

**Just thought I would post this don't know if it would help.**

**Comment by SteffeyDev** [comment]
Deleting that will cause it to fail when you send audio commands, not a huge deal if you don’t care about audio controls. I’ve been having issues with my build environment and not been able to test for several minutes. With info, I may be able to fix, we’ll see if I can spot the core issue.

**Comment by zackdickinson16** [comment]
Yes I don't really care about audio commands right now. I'm just happy it's working. And that's great thanks a lot!.

**Comment by SteffeyDev** [comment]
@zackdickinson16 Please try 3.0.4, your screenshot above helped me find a bug that may fix your issue

**Comment by zackdickinson16** [comment]
Yes this fix the issue of it crashing on startup when connected to a switcher.
It still says **"Could not get IBMDSwitcherAudioMixer interface"** I don't know if this matters?

I tried it on a ATEM Mini and ATEM Production Studio 4k and both seem to work fine.

**ATEM Production Studio 4k
ATEM Switchers 8.1.1
OSC v3.0.4**
![Screen Shot 2020-04-12 at 7 55 42 PM](https://user-images.githubusercontent.com/57646814/79081981-a4646d00-7cf8-11ea-9741-0c61b97d1be4.png)

**ATEM Mini
ATEM Switchers 8.1.1 and 8.2
OSC v3.0.4**
![Screen Shot 2020-04-12 at 7 58 57 PM](https://user-images.githubusercontent.com/57646814/79081998-d07fee00-7cf8-11ea-997d-efb4290a5f89.png)

**Comment by SteffeyDev** [comment]
That's just a warning, it is safe to ignore.  Thanks for testing! I'm going to close this issue as resolved, open a new issue if you have any additional problems
