### ISSUE TITLE
Record (and stop recording) on ATEM Mini Pro

### ISSUE THREAD

**Issue by 2xbass** [danielbuechele/atemOSC#158]
It would be really great if we could get the ability to start and stop recording on the ATEM Mini Pro. We have the ability to record through the Hyperdeck but the Mini Pro has the ability to record to a disk (and in fact even a bank of disks) through its USB-C port. I’ve only ever tried with one disk but the announcement video for the Mini Pro showed that it’s possible to choose from different disks and record to different ones.

**Comment by SteffeyDev** [comment]
Can you make a Macro that starts and stops recording? If you can make a macro, you can use atemOSC to trigger that macro.

**Comment by mkcologne** [comment]
Unfortunately the Mini Pro can't do Macros.

**Comment by SteffeyDev** [comment]
It can do macros, you just have to set them up using the ATEM software on a nearby Mac or Windows PC. Once the macro is set up, you can use atemOSC to trigger it without having the software open or even the external PC powered on.

**Comment by SteffeyDev** [comment]
I’ll mark this as a feature request, just want to make sure you don’t get held up waiting for us :)

**Comment by mkcologne** [comment]
Thanks. I usually work an big Mixers (GrassValley, Belden, Sony ...) and so I've tried a komplex one. So only Simple stuff seem possible, or is there a way to set a pause, or run a macro inside an macro to combine them? Cheers - M.

**Comment by SteffeyDev** [comment]
I’m not familiar with the capabilities of your switcher or creating macros in general, but were you able to make a macro to start/stop the recording?

**Comment by mkcologne** [comment]
For my questions this ist the wrong Thread. Thanks for ur help. Will continue @blackmagic. 
Cheers - M.

**Comment by SteffeyDev** [comment]
Ah I didn’t look and assumed you were the OP. My mistake

**Comment by mkcologne** [comment]
So I found out: the Macros are inside the Project_XML and there you can do much more than you can record. E.g.: A pause can inserted with a simple line:
<Op id="MacroSleep" frames="1"/>

So its easy to record simple Start/Stop Macros, or add it in the XML with:
<Op id="RecordToMedia" start="<True/False>"/>

**Comment by 2xbass** [comment]
I was able to create a macro to do this so I'm good now.

**Comment by cayblood** [comment]
Does anyone know if it's possible to _pause_ recording on an ATEM Mini Pro ISO? This is a really handy feature when recording computer demos and you don't want to have to cut sections in post-production.

**Comment by pixelwiz** [comment]
> Does anyone know if it's possible to _pause_ recording on an ATEM Mini Pro ISO? This is a really handy feature when recording computer demos and you don't want to have to cut sections in post-production.

I'd really like to see a Pause Recording option too
