### ISSUE TITLE
Selecting Aux sources

### ISSUE THREAD

**Issue by fred-dev** [danielbuechele/atemOSC#16]
Hi, I am using the latest atemOSC (2.4.4) with an ATEM 1/ME Running firmware for 6.6.1and all is going well, but I can only select black as an aux sources. I am using the correct address (as I can select black on any aux when it starts on a different selection), however when I change the int payload to anything else I cannot select a source (eg any of the camera inputs).

Cheers

Fred

**Comment by sneat** [comment]
Hi @fred-dev 

It should work correctly. What's the exact command you're sending, and what are you using to generate the command? 

I'm going to guess that you're only sending through `0` as the actual value being sent to the address.

I regularly use [sendOSC](https://github.com/yoggy/sendosc) to change my AUX sources without an issue.

The following example would set AUX 5 to be SuperSource
`sendOSC -h 127.0.0.1 10000 /atem/aux/5,6000`

**Comment by fred-dev** [comment]
Hey, I am using a program called Isadora, I will switch to making something with open frameworks for further testing.

I am sending
atem/aux/1 then with a integer (I am only looking to get my camera inputs from the aux so I use 1 - 6)
so eg  atem/aux/2 5

As I said it works fine to select black (this is when I am sending 0 as the value), when I change the value I can’t select an input. I did not try the extended selections like 6000 yet though.

Fred

**Comment by sneat** [comment]
See if you can replicate it using a different program, and if you are willing to send the config you are using then I can try doing some debugging.

**Comment by fred-dev** [comment]
Cheers I'll check it out, I cant test with the atem again for a few days
but if you are running this release and changing it I am guessing it may be
the software I  sending from.

**Comment by tomroosen** [comment]
Hi,

I have the same problem with the auxes, no matter what I try, I only got black. I'm using OSCulator to send the oscillator messages.
The OSC message that I'm sending is: /atem/aux/1 <1>
So I want to set input one to aux one.

I think I got something wrong :(

**Comment by sneat** [comment]
@tomroosen can you give v2.4.6 a go from the following fork? https://github.com/LanSmash/atemOSC

**Comment by tomroosen** [comment]
Is it possible that i'm using the wrong osc command? 
<img width="631" alt="schermafbeelding 2017-05-17 om 11 26 22" src="https://cloud.githubusercontent.com/assets/28686620/26147405/bcfa3790-3af3-11e7-8e3e-a2b043bb7c89.png">

**Comment by sneat** [comment]
It's possible. I haven't used OSCulator before to know whether what you have there is trying to send the address `/atem/aux/1 <2>` with no parameters/values, or if it's sending the address `/atem/aux/1` with one parameter with a value of `2`.

If it's the first, it won't work correctly, if it's the 2nd, it should be working.

Can you please paste the output of the Log window (Help->Log). You should see something like `[2017-05-18 07:59:48] Received OSC message: /atem/aux/1	Value: <OSCVal i 2>` when atemOSC receives a message.

On the assumption that the wrong message and value are being sent, you can use a combination of that Log window and OSCTestApp (http://vdmx.vidvox.net/blog/freebies#block-yui_3_17_2_1_1455291714896_128700) to adjust the OSCulator properties until it's correct. To use OSCTestApp, enter details like the following (change the IP/port obviously) and when you put `2` into the "Send Int:" box, press enter to actually send the command

![image](https://cloud.githubusercontent.com/assets/293277/26178024/8cc1beca-3b9f-11e7-864a-97e63b8923f2.png)

Finally, if it is an issue with the values in OSCulator, would you mind providing a sample save file that has working commands and we can add it as an example going forward.

**Comment by tomroosen** [comment]
Thanks for all your support! The solution was easier than I thought. Thanks to the help of John Barker from [heretorecord.com](heretorecord.com) and Sneat the solution was found.
<img width="442" alt="screen shot 2017-05-18 at 18 40 08" src="https://cloud.githubusercontent.com/assets/28686620/26216044/f6f8b88a-3c02-11e7-8163-f9caa8e5a830.png">

**Comment by sneat** [comment]
Cool, glad you got it sorted :)

**Comment by SteffeyDev** [comment]
Closing because resolved
