### ISSUE TITLE
OSC control volume faders

### ISSUE THREAD

**Issue by Christoph111** [danielbuechele/atemOSC#160]
hi, thanks for your great work, i successfully control most of the functions of the atem mini pro with toucOSC.
but i can not manage to adjust the volume faders at all.
Even when i connect to osculator and move the faders, all messages look exactly the same.
/atem/fairlight-audio/source/-65280/ for every channel....

The output fader is working /atem/fairlight-audio/output/gain

what am i doing wrong? thank you

**Comment by SteffeyDev** [comment]
Fairlight audio support is currently being implemented and tested, you can track the progress of this feature in #150 and participate in testing as well.

**Comment by ruebyi** [comment]
Hi!
Any news on this?
Companion just managed to add Fairlight audio Control of different Sources etc.
At the moment I need an seperate MIDI Contorller with Mackie controls to Control my faders of the ATEM Mini Pro.

**Comment by xenonheavyindustries** [comment]
Please dont start up with companion bullshit. Use that if you want, but dont bring that nonsense in here. Most of their users are the absolute lowest common denominator. Spamming an issue thread with "is it done yet?" and trying to play the devs off against other projects is lame.

**Comment by ruebyi** [comment]
I‘m sorry if I offended anyone. 
I’m just searching for workarounds, so I mentioned the other project.

**Comment by xenonheavyindustries** [comment]
Nice non-apology👌 Maybe roll up your sleeves and contribute some code
