### ISSUE TITLE
Auto timing/duration osc float

### ISSUE THREAD

**Issue by high-solutions** [danielbuechele/atemOSC#164]
hi,

I'm looking how to change the auto transition timing, so not using the "bar" but just say something like:
/atem/transition/set-type/mix
/atem/transition/time 8
Or:
/atem/transition/auto 8
Or: 
/atem/transition/ftb 8

so the timing should/could be 8 seconds in these examples
i hope i made my self clear, is this possible?

My main goal is to define a auto transition time per cue in Qlab sending osc

**Comment by sneat** [comment]
You could record macros setting different transition timings and then have atemOSC trigger the appropriate macro when you need?

**Comment by high-solutions** [comment]
Hi! Thanks for the response. I could do that but that's really bad for the workflow, in the theater performances with mostly light, video and audio combined i sometimes need to adjust the video fade to be in sync with the afterglow of lamps for example. It would be much faster to change a value in the osc command instead of recording hundreds individual macros for individual cue's.

I am now trying to make a work around with the bar.
I can "fade" the bar and adjust the time of how long this wil take in qlab but this is not working right yet because the bar works as an a/b fader (so sometimes the zero value is preview and the 1,0 value is program and sometimes it's the other way around) whats great if you have an actual fader but the way qlab thinks how a transition wil be is from 0 to 1 and the next time als from 0 to 1 instead of 1 to 0. 
I can make this work but it's complicated and sometimes if the bar is a little bit off at the start it cuts hard to the previewed cam and then makes the transition back to the previous camera.

There are a lot of work arounds but they are not great and take a lot of time.

**Comment by SteffeyDev** [comment]
Should be a pretty basic feature, I might be able to knock it out real fast today.

**Comment by SteffeyDev** [comment]
@high-solutions, please try https://github.com/danielbuechele/atemOSC/releases/download/v3.1.4/atemOSC_3.1.4.dmg

I'm unable to test, so let me know if it allows you to set the rate using `/atem/transition/rate <float>`

**Comment by high-solutions** [comment]
You sir, are my hero!

For me this works like a charm, noted that it only works on the mix transition.
Atem software use different rates for different transitions (also in their own macro system, you can't make a macro to change the rate to 3 and use it in what ever transition style you have selected. If you made the macro in mix and then select dip or wipe and use the macro it wil still change the mix rate in the background).

I don't mind very much because i will mostly use the mix transition with this osc command.

But maybe it would be great to implement more rate values for example the: 
USK & DSK (fade in/out)Rates (weird enough the USK rate is one rate for luma/chroma/pattern and DVE)
Respectively the Dip/Wipe and DVE rates.
I guess the stinger rate is not so useful without the rest of the stinger functions.

But maybe i'm asking to much right now ;)

**Comment by SteffeyDev** [comment]
Challenge accepted: https://github.com/danielbuechele/atemOSC/releases/download/v3.1.5/atemOSC_3.1.5.dmg

Use `/atem/transition/rate <float>` to set for current type, or you can use `/atem/transition/mix/rate` to set for mix specifically.  Same for `wipe`, `dve`, and `dip`.  Also added `/atem/dsk/#/rate <float>`.  Couldn't find a parameter for USK except for Fly Rate, which I don't understand enough to implement.

**Comment by SteffeyDev** [comment]
Once you verify it works, I can switch that to a public release (it's pre-release right now)

**Comment by high-solutions** [comment]
Strange. switching works for mix, dip and DVE but not for the wipe transition. great work tough.
The DSK rate works nice. 

And you are right about the USK rate, in my way of thinking i could use it to transition the USK but it is indeed a function of the flying key so thats an other topic.

**Comment by high-solutions** [comment]
https://github.com/danielbuechele/atemOSC/commit/75b6757e57c95f89256f7009c3106323aa913b1d#diff-523cb9e3407ad911a5c675b7350a27b5 
in line 214 there is a copy paste typo, it should be wipe instead of dip:

> if (SUCCEEDED([appDel mMixEffectBlock]->QueryInterface(IID_IBMDSwitcherTransitionDipParameters, (void**)&mTransitionWipeParameters)))

**Comment by SteffeyDev** [comment]
Ah good catch. Does `/atem/transition/rate` work for switching the currently selected type?

**Comment by high-solutions** [comment]
Yes, it works like a charm (except for the wipe :p)

**Comment by SteffeyDev** [comment]
Ok, just released 3.1.6, which should have everything working now

**Comment by ruebyi** [comment]
Sorry for add something here:
Would it be possible to put this command on a poti on my xTouch mini so I could give out different Rates when turning the poti?
