### ISSUE TITLE
Could not create Switcher Discovery Instance. ATEM Switcher Software may not be installed

### ISSUE THREAD

**Issue by FrankyFlow123** [danielbuechele/atemOSC#165]
Ich weiß nicht mehr **weiter...**

Nach einem Update der AtemOSC-Application von 2.5.7 auf 3.16 kommt immer die Fehlermeldung. Ich habe alles Mögliche ausprobiert..

System: High Sierra 10.13.6

Atem: 8.03
Software Control: 8.1

Ist irgendwo ein Denkfehler? Die ATEM-Software habe ich mehrfach deinstalliert und neu aufgespielt. Die IP-Adresse funktioniert. - Zumindest auf dem Windows-Rechner, welcher das ATEM betreibt. 

Passen ggf. die Versionen der Software nicht zur Application?

Welche Version der BlackMagic Software wird von der App unterstützt?

Ich danke Euch für Anregungen.

**Comment by FrankyFlow123** [comment]
@danielbuechele  - Kannst Du das erklären?

**Comment by dolbytx** [comment]
Having this issue too. I have a Mac mini 10.14.6 with an ATEM 1 M/E with 8.01 control software. Please advise. Thanks

**Comment by daukema** [comment]
Also having this issue. iMac with Mojave 10.14.16, ATEM Television Studio HD, 8.3 Control Software.

**Comment by sempei13** [comment]
Same problem here. ATEM software control 7.5.2; Catalina 10.15.6; OSCulator 3.4.1; 2019 16" Macbook pro

**Comment by sempei13** [comment]
OK, here's what worked for me.  I upgraded my Control software and ATEM Television Studio HD to 8.4.  Then it worked as expected.

**Comment by FrankyFlow123** [comment]
Das Problem hat sich ergeben bzw. gelöst.

Auf dem Mac (der als Schnittstelle zum ATEM OSC zwischen einen iPad mit der OSC-Midi-Touch-Software dient) war keine ATEM-Software vorhanden. Diese muss auf dem Mac und auf dem Windows-Rechner exakt die gleiche Version haben. Wenn dann beide Rechner (WindowsPC und MacBook) im selben Netzwerk sind, funktioniert auch das ATEMOSC, sowie die Touch-Pad Software (vorausgesetzt die Files sind richtig synchronisiert und im richtigen Netzwerk)

Bei Fragen: Gerne
