### ISSUE TITLE
OSC feedback is missing

### ISSUE THREAD

**Issue by fred-dev** [danielbuechele/atemOSC#17]
Hi, I am using the latest atemOSC (2.4.4) with an ATEM 1/ME Running firmware for 6.6.1, I am not sure if it is meant to be present but I don't get OSC feedback from your app for most of the controls. I do get program and preview input assigns as well as the tbar position, but I don't get aux info or any other data for keys, auto cut etc. Is this the correct behaviour?

Cheers

Fred

**Comment by sneat** [comment]
Most features don't have feedback support yet. There's an existing ticket requesting a similar thing https://github.com/danielbuechele/atemOSC/issues/13

**Comment by SteffeyDev** [comment]
Closing this in favor of more specific feedback needed, open a new issue if feedback is desired for a specific endpoint.
