### ISSUE TITLE
Controlling more than on ATEM mixer

### ISSUE THREAD

**Issue by richieclare** [danielbuechele/atemOSC#182]
Hey there

Is it possible to control more than one ATEM mixer from the same machine? I have been using atemOSC successfully with a TV Studio HD but have recently purchased a mini pro so I can record and stream - I was hoping to be able to do switching etc on the TV Studio but have the ability to play a macro on the mini pro that would start and the stop the stream/record. 

Thanks

Richard

**Comment by SteffeyDev** [comment]
See #170
