### ISSUE TITLE
Only fade to black transition works with BlackMagic Television

### ISSUE THREAD

**Issue by no-wa-ke** [danielbuechele/atemOSC#19]
I tried to call transition addresses, but none of them works with Blackmagic television studio except for 
```
/atem/transition/ftb
```

Is this hardware related problem or something that could be fixed with communication protocol?

**Comment by no-wa-ke** [comment]
Nevermind, it was osc-client's problem. I was able to trigger auto after I used TouchOsc preset.
But there is one more problem... I tried to add 
```
/atem/transition/set-style/foo
```
to TouchOsc, but none of them seems to be working...

**Comment by sneat** [comment]
I've successfully used [sendOSC](https://github.com/yoggy/sendosc) with the following commands without issue:

```
atem/transition/set-type/mix
```

```
atem/transition/set-type/sting
```

```
atem/transition/set-type/dip
```

```
atem/transition/set-type/wipe
```

**Comment by no-wa-ke** [comment]
Thank you sneat for the solution! they worked like a charm.
Adding these addresses to the documentation would be nice.

**Comment by sneat** [comment]
@no-wa-ke they are in the documentation? Both in the readme (just under the input list) and also in the app's help menu.

**Comment by no-wa-ke** [comment]
@sneat Sorry, I meant adding 'set-type' to README.md would be nice!
