### ISSUE TITLE
/atem/usk/1 needs an argument to work

### ISSUE THREAD

**Issue by keezpipslab** [danielbuechele/atemOSC#22]
Hi there,

For me the upstream keyers only work if I add an int argument of 1..
In openframeworks:

  ofxOscMessage m;
 m.setAddress("/atem/usk/1");
  m.addIntArg(1);
 senderAtem.sendMessage(m);

/atem/program/1 works fine without.

kz

**Comment by sneat** [comment]
Some of the endpoints require values to be sent. https://github.com/danielbuechele/atemOSC/blame/master/atemOSC/SwitcherPanelAppDelegate.mm#L401 requires any float value (number) that isn't 0.

**Comment by SteffeyDev** [comment]
Probably should be more specific in README that all endpoints not marked with `<1|0>` require a `1` to be sent.  But still closing this issue because resolved.
