### ISSUE TITLE
Switcher IP address is lost at startup

### ISSUE THREAD

**Issue by jeffmann** [danielbuechele/atemOSC#23]
atemOSC is not restoring the switcher's IP address when it starts. Steps to reproduce:

1. Open atemOSC and enter the required IP addresses and ports.
2. Note that switcher is successfully found, and operations are correct.
3. Note that ~/Library/Preferences/cc.buechele.atemOSC.plist contains the correct IP address.
4. Quit atemOSC.
5. Note that the preferences file is still correct.
6. Start atemOSC.

Actual behaviour: the OSC IP address and ports are correct, but the Switcher IP address is missing. No connection is made to the switcher. A new file named "~/Library/Preferences/cc.buechele.atemOSC.plist.12a34bc" (i.e., with a random extension) is created, and then renamed to replace the original preferences file. The Switcher IP address must be manually entered every time atemOSC starts.

Expected behaviour: the Switcher IP address is restored correctly from the preferences file, and no changes are made to the preferences file.

Other observations:

- If you quit atemOSC, trash the preferences file, then re-open atemOSC, it will still contain the OSC IP address and ports. I don't know where it gets them from, presumably the application is not fully terminated. If you restart the computer after trashing preferences, all data is blank as expected.
- If you quit and replace/edit the preferences file with different values, then re-open atemOSC, it will not read the preferences file. It will have the values last set in the application before quitting, except not the Switcher IP address. It will then replace the edited preferences file with those values, including the blank Switcher IP address.

Using macOS 10.12.3 with a manual IP address and an Ethernet cable directly to an ATEM Television Studio HD.

**Comment by diegocas2008** [comment]
Im having this same issue. After a reboot the IP address is gone. not hard to put it in but easy to forget.

**Comment by SteffeyDev** [comment]
@diegocas2008 I think I fixed the issue in the commit referenced above, watch for PR #44 to go through and for the next version.

**Comment by diegocas2008** [comment]
@SteffeyDev Hey! ok cool. Im not very good at all this, so im not sure where or what im looking at. Do i copy and paste that into terminal?

**Comment by SteffeyDev** [comment]
Oh sorry, no, unless you know git pretty well and have Xcode installed to build the new version yourself, you will have to wait until we release the next version.  I'll try to remember to ping you when that happens.

**Comment by SteffeyDev** [comment]
@diegocas2008 We just released a new version (2.5) which includes a potential fix for this.  Can you try it out and see if it resolves your issue?

**Comment by diegocas2008** [comment]
Thanks man! I'll let you know
