### ISSUE TITLE
Media player source not changing

### ISSUE THREAD

**Issue by natepelzel** [danielbuechele/atemOSC#24]
Hey! Thanks for the awesome software.  It saved us tons of money.  I have an ATEM 1 M/E running 7.0.3.  Pretty much everything works, but I've had some issues setting media source.  I get the following message in terminal when I send the command:

4/16/17 1:04:29.920 PM atemOSC[320]: Received OSC message: /atem/mplayer/1/still/1	Value: (null)
4/16/17 1:04:29.921 PM atemOSC[320]: Could not set media player 1 source

I have tried setting the first argument to 1, bit as int and float, and received the same message in Console.

Is there any more troubleshooting I can do or information I can provide to help fix this issue?

Thanks,

Nate

**Comment by sneat** [comment]
I'm not near a computer right now, but can what are you using to send the OSC command? Can you test with the following command please? It will send a value of 1 through. 

`sendOSC -h <ip> <port> /atem/mplayer/1/still/1,1`

**Comment by natepelzel** [comment]
Sorry for taking a while to get back, I've been out of the office so I have not had access.

I was originally using OSCulator to send the OSC command.

I tried the command you suggested (using [this utility](https://github.com/yoggy/sendosc)), and I did not receive any feedback in the terminal, but the same message was logged in console.  For reference, that message is:

```
4/19/17 1:26:42.387 PM atemOSC[320]: Received OSC message: /atem/mplayer/1/still/1,1	Value: (null)
4/19/17 1:26:42.388 PM atemOSC[320]: Could not set media player 1 source
```

I also tried playing around with the sendosc utility and ran:

```
sendOSC <ip> <port> /atem/mplayer/1/still/1
```
```
sendOSC <ip> <port> /atem/mplayer/1/still/1 i 1
```

And they both logged the same error.  Again, no response in the terminal.  The utility I was using did not require the '-h' flag, so I'm not sure if there's a different one that I should be looking at, though.

Thanks for the help!

**Comment by sneat** [comment]
@natepelzel I've created a PR for the fix (Blackmagic updated their SDK and broke the compatibility - the same code needed to run, but it no longer triggered anything to happen on the ATEM).

In the mean time, you can grab a copy from my fork https://github.com/lansmash/atemOSC

**Comment by natepelzel** [comment]
Thanks!

I tried it out and it did resolve the issue.  It also resolved an issue I was having with tying the  DSKs.

Again, many thanks.
