### ISSUE TITLE
Switcher is Double Running DSK auto functions

### ISSUE THREAD

**Issue by JessicaAE** [danielbuechele/atemOSC#26]
hi, im running the switcher with a Korg Midi Pad Controller, when i run a DSK auto button it will sometime run again at a random interval after the key press, between 1 and 6 seconds usually.

everything else works perfect and the switcher is still running and working with all other commands.

its an ATEM Television studio with latest software. and on a mac mini 2010.

**Comment by sneat** [comment]
@JessicaAE are you able to test using OSCulator or sendOSC to rule out the controller as the issue? Use one of those programs to manually send a single OSC command and see if you can replicate it triggering multiple times please.

**Comment by JessicaAE** [comment]
i did and i think it came down to a latency issue with the local machine.

it seems to work now as long as atemosc is open and the primary window

**Comment by sneat** [comment]
Ok, thanks for the feedback.

**Comment by SteffeyDev** [comment]
Closing because it seams resolve, @JessicaAE you can open a new issue if you run into this issue again and can confirm that it is an issue with AtemOSC and not the controller.
