### ISSUE TITLE
BKGD, FTB and DSK issues on ATEM 1 M/E Production Switcher

### ISSUE THREAD

**Issue by JamesFrank2525** [danielbuechele/atemOSC#31]
Hi Daniel,

I'll get straight to the point(s):
1. OSC Command for BKGD does not work. I typed correctly /atem//0 (which is the command atemosc advised me to type) but there is no reaction from the ATEM whatsoever.
2. FTB and DSK's are crazy. When I push ftb, it dims a little and then goes back to previous state. When I push DSK Tie or DSK Toggle, it lights up for a fraction of a second and then disappears. If I press it multiple times, sometimes it remains for a few seconds, sometimes remains for good. If I press DSK Auto, it fades in and then immediately fades out. Or again, sometimes it remains. There is no rule about this behavior.

I am using atemOSC v2.4.7, OSCulator 3.1.1, and MIDI Controller AKAI APC Mini.

**Comment by SteffeyDev** [comment]
Ok so I’m not a project creator but experimenting has shown me that ftb and dsk is doing that because the button you are pressing sends “1” on touch down and “0” on touch up, so it is not random but actually the time period you are holding the button for. You need to program the button to only send “1” on touch down and nothing on touch up, and then ftb and dsk will work correctly (auto toggle on button press). I don’t know why it functions this way but it works for me

**Comment by SteffeyDev** [comment]
Note the above is only for DSK auto, tie should work normally

**Comment by JamesFrank2525** [comment]
But in OSCulator Note On has different MIDI message than Note Off and I only assigned Note on messages to OSC commands. Moreover, other on/off buttons work correctly with the same settings (like USK On Air).

**Comment by SteffeyDev** [comment]
Can you post the actual OSC commands that atemOSC is receiving?  That would help to figure out what is happening behind the scenes. AtemOSC has a logger built in under the help menu (though it has a tendency to crash, working on that fix still)

**Comment by JamesFrank2525** [comment]
Looking into log was a good idea. You were right, OSCulator still sends double commands. I changed the conditions in OSC commands to send it only when value increases and now OSCulator sends single commands. I will check it with the ATEM as soon as I'm home and will let you know how it performs. Thank you!

**Comment by SteffeyDev** [comment]
@JamesFrank2525 Did you get the chance to test yet to see if this solves your problem?

As for your question #1 above, I think you have a typo, because “/atem//0” is not a valid command.  Did you mean “/atem/usk/0” or “/atem/nextusk/0”?

**Comment by JamesFrank2525** [comment]
Indeed, I had great opportunity to test everything during Fight Night live streaming, and it actually worked great. The only issue I had was MacBook losing connection with ATEM, but I think it was due to its WiFi connection - next time I'll just connect to the router with wire (I need router in order to run Unity Intercom app with tally). Thank you again for your help!

You are probably right, what you are writing seems logical. Still, "/atem//0" is a OSC command listed in the official atemOSC help after I connected my switcher. I will test how "/atem/nextusk/0" works - please remember to write it in atemOSC help.

**Comment by SteffeyDev** [comment]
Oh, you are correct about it being in the help documentation, I didn't even see that, I will create a new issue to investigate why it says that.

**Comment by SteffeyDev** [comment]
Closing issue in favor of #37.
