### ISSUE TITLE
Help documentation: Fix /atem//0

### ISSUE THREAD

**Issue by SteffeyDev** [danielbuechele/atemOSC#37]
For some reason, in the code it has:
`[helpString appendAttributedString:[[NSAttributedString alloc] initWithString:[NSString stringWithFormat:@"/atem//0\n"] attributes:infoAttribute]];`

I think this is supposed to be

`[helpString appendAttributedString:[[NSAttributedString alloc] initWithString:[NSString stringWithFormat:@"/atem/nextusk/0\n"] attributes:infoAttribute]];`

@danielbuechele or @sneat  can you confirm?

It may also have meant to be /atem/usk/0

This was first identified in Issue #31

**Comment by sneat** [comment]
I agree, it should be `/atem/nextusk/0`
