### ISSUE TITLE
Setup Github Release for each SDK Version

### ISSUE THREAD

**Issue by SteffeyDev** [danielbuechele/atemOSC#40]
We need to go back through history and tag the last commit before an update to the SDK, and then label these tags with the SDK they are supporting.  Then we can setup an official release for each SDK version and people can find the version for their SDK very easily.

**Comment by sneat** [comment]
One thing to note is that often there aren't actually changes between the SDK's (at least as far as atemOSC cares).

**Comment by SteffeyDev** [comment]
Ok, do you know what SDK versions did have breaking changes, so that we can tag those specifically?

**Comment by sneat** [comment]
Nah, each time it's a matter of diff'ing the .h and .mm files that are part of it and seeing if there's anything relevant. It'll be easier to just say that they are for the version of whatever SDK (even if it's slightly incorrect - in that more versions are actually supported).

**Comment by SteffeyDev** [comment]
Gotcha, that makes sense
