### ISSUE TITLE
Removing tally interface

### ISSUE THREAD

**Issue by danielbuechele** [danielbuechele/atemOSC#42]
As mentioned somewhere else, what do you think of removing the tally interface? This was a fun little thing I built based on an Arduino, but I didn't ever use it in production.
The software is very custom to my implementation of the hardware. I think it would create cleaner code, UI and docs if we just remove this.

**Comment by SteffeyDev** [comment]
I honestly don't know exactly what it does, what was the purpose of the tally interface?

**Comment by SteffeyDev** [comment]
Ok, after looking it up I agree that it should be removed for the time being, of course kept in git history in case it wants to be revived later on.
