### ISSUE TITLE
Update In-App help menu with all OSC addresses from README

### ISSUE THREAD

**Issue by SteffeyDev** [danielbuechele/atemOSC#49]
The in-app help menu 'OSC Addresses' has been lagging behind the changes in the project, and needs to be updated.

**Comment by danielbuechele** [comment]
I was thinking if there is any way we could ensure this is always in sync. Basically there are 3 places there the commands need to be available:
- implementation of the command
- help menu
- readme/website/documentation

I think, the implementation of the command would be the best place, to be the single source of truth. Perhaps we could use some some macros to generate the help menu? Or some doc-style comments.

Theses are just random ideas and I don't know how practical this is, but needing to maintain 3 places when adding a single command isn't good, either.

**Comment by SteffeyDev** [comment]
I’ve been playing with different ideas, the primary issue with doing it in code is that you loose any sort of markdown formatting, which would be fine for internal documentation buy is sub-optimal for a user-facing documentation.  The secondary issue with this is that we’d have to use a third party parser (like doxygen), we couldn’t use macros because macros are only run when the code it is associated with is run, so a macro in the received function would only be run when the corresponding command is received, and thus is not appropriate for generating documentation.

My suggestion is to have a separate markdown file be the primary source of truth, either the README (currently) or a oscommands.md file on the future website.  To access from the app, we could either link to the website (which is common among these sorts of projects) or use an Objective-C markdown renderer in a window.  We could also use a web view but that seems a bit cheesy.

When I was first learning the app, I didn’t even use the in-app OSC menu (even though I knew it existed) because the readme had more detail and nicer formatting.

That being said, with my suggested scheme, we would need the website to track versions, so that uses can go “back in time” to see what this markdown file looked like at an older version.  I believe there are several project website frameworks that have this capability (the docs for react-native-firebase come to mind).

If you wanted to be fancy, you could leave links in the code that point to anchors on the website, but that would be extra.

Let me know how you feel about this, and what pros/cons you see

**Comment by SteffeyDev** [comment]
This should have been resolved by #77
