### ISSUE TITLE
AUX Switching not functioning

### ISSUE THREAD

**Issue by krezlic** [danielbuechele/atemOSC#50]
I have been unable to make the AUX switching function work,
I wish to switch an input to an AUX channel. 

AtemOSC 2.4.7

Using Sample Template ( Advanced Video Control ) or building my own.

Set Aux $i source to $x /atem/aux/$i $x
Where $x is a valid program source. Check the Help Menu for the correct values.
e.g. /atem/aux/1 1 to set Aux 1 output to source 1 (Camera 1)
(up to /atem/aux/6 $x, depends on your ATEM switcher)

Is this currently functioning?

**Comment by SteffeyDev** [comment]
This should be working, I’ll check it out when I get access to a switcher tomorrow

**Comment by SteffeyDev** [comment]
Are you using v2.4.7 from the releases page or the latest commit on the Master branch?

**Comment by krezlic** [comment]
Hi, it was from the master release as a zip no building required

**Comment by SteffeyDev** [comment]
@krezlic You are correct that both 2.4.7 and latest commit has broken AUX, I apologize for this and will have a fix in the next release, which will hopefully be in the next week or so.

**Comment by krezlic** [comment]
no worries at all ;) 

by the way have you got the same ability to control a blackmagic router ? be keen to talk about a OSC BMD panel.

**Comment by sneat** [comment]
@krezlic I don't think any of us have access to one. We could guess/program based on the API, but no way to actually test it.

**Comment by SteffeyDev** [comment]
@krezlic I tested fix and made #51, watch for the next release to have the fix in it
