### ISSUE TITLE
Audio controls

### ISSUE THREAD

**Issue by danielbuechele** [danielbuechele/atemOSC#55]
If possible we should expose ATEMs audio controls via OSC, too.
It looks like this information is available via the SDK: https://github.com/danielbuechele/atemOSC/blob/71b2d0fa1cafa8c3faa444636e9ad91143ba1d79/atemOSC/BMDSwitcherAPI.h#L54-L59

**Comment by JamesFrank2525** [comment]
Indeed, in my opinion audio support is the only thing atemOSC lacks.

**Comment by Reimsd** [comment]
I would love to have the addresses for the Audio controls out of the ATEM tvs!

**Comment by SteffeyDev** [comment]
I'm trying to implement, but am running into an issue.  I cannot get the Audio Input Iterator, when I query the switcher it returns an error E_NOINTERFACE.  @danielbuechele @sneat Have you guys had issues with this before?  Feel free to look at my code (https://github.com/SteffeyDev/atemOSC/tree/audio-controls) to make sure I am doing it right.

I have got basic output control (gain, balance) working, so that's a start.

**Comment by jpvh85** [comment]
Just create the audioMixer before the audioinput and take mAudioMixer instead of mSwitcher to create the audio input iterator

**Comment by SteffeyDev** [comment]
@jpvh85 Ah, I hadn't tried that, but it makes sense.  I'll try it out tomorrow. Thanks!

**Comment by SteffeyDev** [comment]
That worked, I'll send a PR soon.

**Comment by distinctit** [comment]
Any update on the audio controllers ? Good day everyone. Great being part of the group.

**Comment by SteffeyDev** [comment]
Audio is done, just not released yet. Still waiting for @danielbuchele's feedback on other issues

**Comment by SteffeyDev** [comment]
@distinctit @Reimsd Just released version with audio support (v2.5.2), very basic with just gain and pan, it would be great if one of you could test and let me know how it works for you.

**Comment by JamesFrank2525** [comment]
Still at home for Easter, but definitely will check it out tonight! Thank you so much!

**Comment by JamesFrank2525** [comment]
Ok, I've tested it and I might be doing something wrong, but for the gain, it only goes from 0 to +1dB, which is just a tiny movement on the slider in ATEM Software Control. (MIDI 0 is 0dB and MIDI 127 is +1dB)

For the balance, it uses its full scale correctly, but only to the right channel (MIDI 0 is the middle and MIDI 127 is +50 to the right channel)

**Comment by SteffeyDev** [comment]
Hm, I haven't tried with Midi, technically we don't support MIDI directly, so it may just be a configuration issue with your MIDI-to-OSC router.  If you have TouchOSC, check out the sample config: https://github.com/danielbuechele/atemOSC/blob/master/samples/Advanced%20Video%20Control.touchosc.  That's what I used to test and I was able to get full range of motion; If you send OSC float value of `-60`, you should get lowest volume, and if you send float value of `6` you should get highest value.  I think you just have to change your MIDI-to-OSC to support this range of values.

I think you have the same issue with balance;  You need to send `-1` to get full left and `1` to get full right.  My gut tells me that your router maps MIDI 0-127 to OSC 0-1, which won't quite work for this directly, so you might have to mess with the config.

Thanks for testing!  Feel free to ask any more questions, I'd love to help you get this working if I can.

**Comment by JamesFrank2525** [comment]
Ok, I forgot to mention that I am using OSCulator. And in the routings window I have space for all arguments, but I don't really understand how it works. Should I add argument at index or a variable? There is a float option, but I still don't know how to make the range from -60 to 6
![zrzut ekranu 2018-04-03 o 13 18 25](https://user-images.githubusercontent.com/32199685/38246278-8e7f01d4-3741-11e8-8187-ca6dfe3ce70b.png)

**Comment by SteffeyDev** [comment]
I don’t know if OSCulator can do it natively, but you could run it through OSCRouter for the scaling: https://github.com/ETCLabs/OSCRouter. I haven’t tested it myself but it looks like it could work. I could make a MIDI specific audio control variant that only goes from 0 to 1, but I would have to think about how the API would work for that.

**Comment by JamesFrank2525** [comment]
Unfortunately, OSCRouter seems to be too complicated for me to configure it. I will keep trying with OSCulator though. If anyone here is also using that software, please let me know how to do this. @SteffeyDev thank you for your amazing work and keep up the good work!

**Comment by SteffeyDev** [comment]
Ok, so I'm thinking we could do something like `/atem/midi/audio/...` with all of the same commands that has the scaling built in, @sneat @danielbuechele How would you guys feel about this?  Basically, it would be a MIDI-specific API that performs the same functions but is more accessible to those sending from MIDI.  Alternatively, I could change the audio API to always except 0-1, though I do like that OSC is powerful enough to have to accept more meaningful ranges of numbers.

**Comment by SteffeyDev** [comment]
Hm, that's an odd issue.  As I doubt it pertains to audio support specifically, can you open a new issue so that we can keep this channel clear for discussing audio control?

**Comment by distinctit** [comment]
I updated to this version for audio controls. So basically this version crashes for me.

**Comment by SteffeyDev** [comment]
I need more details from you, but I don't want to discuss here.  Please open a new issue and post your crash log, version of macOS, version of switcher, and any other relative details. If you post here, I will have to delete, because crash logs take up a lot of space.

**Comment by SteffeyDev** [comment]
Ok, closing this issue and moving the remaining issue to #86.

**Comment by xtonross** [comment]
Tested it. Audio gain and balance control is perfectly working.

**Comment by xtonross** [comment]
Tested it. I used osculator. Audio input for gain and balance is working!
https://youtu.be/aMhtIxTr4M8
