### ISSUE TITLE
atemOSC with ATEM TVS HD 7.2 -- help with setup

### ISSUE THREAD

**Issue by recordandmix** [danielbuechele/atemOSC#65]
Can someone walk me through the setup for this app?

I've downloaded v2.5 and I've got it running under macOS 10.12.6.  I've opened the app, and when I type in the address of my switcher, the "jewel" goes green and the name of the switcher (ATEM TV Studio HD) pops up.  So far, so good.

What goes in the "OSC Out" address?  I am under the impression it's the address from which the OSC commands will be coming.  So if my computer is at 10.0.1.2, I put that address there.

From there, I'm trying to send OSC commands with a (known working) QLab rig.  I send OSC commands back and forth from this app all the time, so I don't think that's the issue.  Which port number should QLab be addressing OSC messages to -- incoming or outgoing?  And if QLab is not listening for responses, do we care what the other setting is set to?

Thanks!

**Comment by SteffeyDev** [comment]
Hi @recordandmix, sounds like you almost have it set up!  The incoming port is the port that atemOSC is listening on, so you should set QLab to send to the `incoming` port. You are correct that you can disregard the `outgoing` port field and the OSC out field if you don't want feedback from the system.

Let us know if you have any issues with running the system.

**Comment by recordandmix** [comment]
Ah, got it working!

Just because this took me a long time to figure out, it's probably worth getting this in the forum (and I'd respectfully suggest making this a lot clearer in the setup documentation):  

If you're in a situation where the computer sending the OSC commands is ALSO the computer that's running atemOSC, the OSC commands need to be directed **at the computer that's sending them, NOT at the ATEM.**  

In my case, I'm running QLab on a Mac with an IP address of 10.0.1.2.  My ATEM is at 10.0.1.30.  I am running atemOSC on the Mac as well.  So to send commands directed at the ATEM, I need to send them to port 3333 *on the Mac*, NOT on the ATEM.  As I type this it makes a little more sense, since atemOSC is acting as a go-between to provide OSC-formatted commands to a device that doesn't natively speak OSC, but it took me a while to figure this out.  I have been sending commands to port 3333 (and, at one point, port 4444) on my switcher's IP address, not understanding that I need to send them to atemOSC's IP address, which, it turns out, is the same as the computer that's generating the messages.

(as an aside, it might be helpful if atemOSC accepted "localhost" as a valid IP address.  I am fortunately using static IPs for my setup, but having to keep chasing your IP address around on show day could be a little stressful.)

I suspect this is a little more intuitive in situations where you've got, say, TouchOSC running on an iOS device -- that you need to direct commands to the "translator" living on a different machine, that will in turn forward them to the ATEM as commands it can understand -- but when the OSC message generator and the translator are on the same machine, the routing is a little less intuitive.

OK...show on Sunday!  Time to start banging on those decks!  Thanks!
Matt

**Comment by SteffeyDev** [comment]
Thanks for letting us know, I honestly hadn’t considered that for the documentation, so I will keep this issue open until we add something.

Just so you know, you can send to 127.0.0.1, which is the equivalent of localhost but in IP address form. 127.0.0.1 is the known as the loopback address, and is present on all computers.

**Comment by recordandmix** [comment]
Oh, right, 127.0.0.1....I didn’t even think of that!  Apple tends to spare us that particular detail...I’m used to seeing “localhost” everywhere & it didn’t occur to me to try the IP address behind it.   Thanks!

**Comment by SteffeyDev** [comment]
@recordandmix I added a section on the README to help clarify, if you have a chance, check it out and see if it would have answered your question!
