### ISSUE TITLE
Chroma Keying Support

### ISSUE THREAD

**Issue by holovicc** [danielbuechele/atemOSC#70]
it would be a great thing to have a midi controller supporting pots to set the values for chroma keying for example.

or is it possible right now, too?

**Comment by jeffmann** [comment]
It's possible right now. You just need another app to translate from MIDI to OSC. You could program it yourself in eg. Python, Processing, or Max, or you could buy [STEIM's junXion](http://steim.org/product/junxion/).

**Comment by SteffeyDev** [comment]
Personally I use OSCulator for MIDI-to-OSC, not sure if it fits your use case though.  I know that atemOSC has no plans of being directly compatible with MIDI because of the wealth of other software that can convert.

**Comment by SteffeyDev** [comment]
@holovicc Does this solve your problem?

**Comment by holovicc** [comment]
I am trying to recall the situation, but i remember like it is AtemOSC that does not offer the chroma key parameters in the list. I am not sure how would junXion or ControllerMate would add these parameters to AtemOSC. (i used OSCulator for getting MIDI into it)

**Comment by SteffeyDev** [comment]
Oh right, that's correct that AtemOSC does not support Chroma Key, I'll leave this issue open as a feature request

**Comment by SteffeyDev** [comment]
Just to check @holovicc, is chroma key support just include Hue, Gain, Y suppress, and Lift?  Do you want the "Narrow Chroma Key Range" check box as well?  Any other parameters?

**Comment by holovicc** [comment]
@SteffeyDev sure, i think having all chroma key parameters accessible would be great help. much easier to work with.

**Comment by SteffeyDev** [comment]
Ok, this is in the master branch and will be available next release
