### ISSUE TITLE
7.4 issue

### ISSUE THREAD

**Issue by carbon43** [danielbuechele/atemOSC#79]
I decided to be your sacrificial guinea pig, and upgrade my switcher and control software to 7.4. 

Can confirm that the OSC Addresses menu is doing the same thing as 2.5 was doing with 7.3.

Assuming the build just needs to be updated to 7.4 support, lmk if I can do anything to help with this, diff etc. Havent gotten into testing if actual control still works yet.

**Comment by SteffeyDev** [comment]
Wow, these BlackMagic updates are coming out fast.  @sneat have you looked into automated releases yet?  If not, we can still release manual.

**Comment by SteffeyDev** [comment]
@carbon43 If you can download https://github.com/SteffeyDev/atemOSC/archive/7.4_update.zip and try out the included app, that would be great.  Definitely see if it fixes the sources and check basic functionality.  It looks like they just added some features so I don't expect anything to break, but always good to check.

**Comment by sneat** [comment]
I haven't had a chance to look at the auto builds yet sorry.

**Comment by SteffeyDev** [comment]
Ok, thanks for the update! Good to hear
