### ISSUE TITLE
Aux always switches to black

### ISSUE THREAD

**Issue by ataylor-orcsd-org** [danielbuechele/atemOSC#83]
Hello,

I have two ATEMs (2 M/E 4k and TVS HD).  This problem exists on both, but I'll only discuss the TVS today.  atemOSC 2.5.2 and ATEM 7.3

atemOSC is sucessfully connected to the ATEM, but whenever I send an OSC message it switches to black instead of the specified input.  I'm using QLab to send the command.  Here's the info below:

QLab: /atem/aux/1 5

atemOSC Log: [2018-04-19 18:52:42] Received OSC message: /atem/aux/1	Value: <OSCVal i 5>

That all looks correct from what I've read, but the switcher has Aux 1 set to Black.

This worked with atemOSC 2.4 and ATEM 7.2 - Does anyone know what I'm missing with the current versions?  Any help would be greatly appreciated.

Thanks,
Alexander

**Comment by sneat** [comment]
What version of QLab are you using and can you paste a screenshot of the settings of the cue you're triggering?

**Comment by SteffeyDev** [comment]
Go ahead and have QLab send float values, integers aren't fully supported for atemOSC.

**Comment by ataylor-orcsd-org** [comment]
Ah okay!

I'm running QLab 4.1.2

Changed the OSC message to be /aux/atem/1 5.0 and it worked!

Thanks again!

**Comment by SteffeyDev** [comment]
Glad it worked! I’m investigating the int/float issue again, and I think I’ve found the issue, so stay tuned.

**Comment by sneat** [comment]
We should update the documentation then to say to send a float (currently it says to send an int)

**Comment by SteffeyDev** [comment]
Actually, I have something better (#84)
