### ISSUE TITLE
MIDI-specific Audio Controls

### ISSUE THREAD

**Issue by SteffeyDev** [danielbuechele/atemOSC#86]
Pulling from #55 

Currently, the `gain` and `balance` values from the OSC audio commands are sent directly to the underlying SDK, so the `gain` is in `dB` and the balance is `-1` for full left to `+1` for full right.  However, this is difficult for users of OSCulator who can only map MIDI to OSC with float values in the range `0-1`.

One option is to make a midi-specific sub-API that would do the scaling from `0-1` to the needed `gain` and `balance` values for the SDK.  I'm open to other suggestions as well.

The API I am imagining is something like `/atem/audio/midi/input/1/gain`, but once again that is open to discussion.

**Comment by xtonross** [comment]
The input range can be customised in Osculator. You can do it by adjusting the Input Min and Input Max
parameters in the Scalings page.

**Comment by SteffeyDev** [comment]
Because OSCulator and I'm sure other OSC apps have the scaling ability built in, I'm closing this issue.  Feel free to re-open if there is a use case that would require a midi-specific API.
