### ISSUE TITLE
Akai APC Mini, OSCulator and ATEM 1 M/E Production Switcher

### ISSUE THREAD

**Issue by JamesFrank2525** [danielbuechele/atemOSC#87]
I create this thread to address certain issues I’ve stumbled upon while configuring my stuff. It is pretty easy to set up TouchOSC, but OSCulator is a bit more tricky so I’m looking for some experts who also uses OSCulator and can teach me how to solve my issues. 

So, let’s start from the very beginning. My current workflow is: AKAI APC Mini > MacBook > OSCulator > atemOSC > ATEM 1 M/E Production Switcher. 

First important fact: ATEM SOFTWARE 7.4 DOES NOT WORK WITH 1 M/E PRODUCTION SWITCHER. LAST VERSION IS 7.3.

Now, here’s my current layout:
![img_0028](https://user-images.githubusercontent.com/32199685/39135612-9fb883ac-4719-11e8-899e-ce63c8c1ccd4.png)

I’ve also written feedback commands for the LEDS. Colors of the frames above correspond with LED colors. The lights don’t change, but are still very useful. If you want the OSCulator file for this, I can send it. Please note that it is written for my old switcher and has to be modified for newer models.

Now, to the point:

ISSUE 1 -  Upstream keyers can only be tied. When I press the button again, it remains tied instead of turning off as it would be in case of DSK. Also, /set-nextusk/ works exactly the same as /nextusk/
REASON - USK tie when OSC value increases and untie when it decreases
TEMPORARY SOLUTION - I’ve created separate buttons for untieing background as well as usk's. They have the same osc command as the tie ones, but are set to react then the value decreases.
@SteffeyDev opened #85 for this issue exclusively.

ISSUE 2 (Audio) - MIDI sliders only work in the range from 0 to 1db. 
REASON - OSCulator only sends OSC values ranging from 0 to 1. Also, all values added to the OSC command are ignored. So, command “/atem/audio/input/5 -60.0” won’t make the slider go all the way down.
TEMPORARY SOLUTION - I pluggged my Korg Nanokontrol 2 directly to the iPad via usb to lightning adapter and mapped it into TouchOSC. Works nice, but it would still be better to control everything through OSCulator so I treat it as a workaround. There might be a solution to this in arguments section of OSCulator, but I don’t understand how it works so I’d be grateful for some upper level knowledge about it ;)

EDIT: Korg sends midi to TouchOSC, faders move, but don't send OSC. Only touching iPad allows me to send OSC. How to make physical MIDI surface also send OSC?

@SteffeyDev opened #55 for this issue exclusively.

That’s all for now, I thought it would be good to open a thread solely for the OSCulator users. Correct me if I’m wrong.

Cheers!

**Comment by Kauffmann9006** [comment]
Hi James,

Thanks for opening this thread. I recently started trying to link my Akai APC Mini to my ATEM Television Studio using OSCulator. 

Apparently we are the only two people on the web that ever tried this.

As it seems I've hit some issues of myself as well and I was wondering if you could share your OSCulator save file so I could check it with mine. Maybe together we can help eachother in the future ;-)

Kind regards

Jonathan Kauffmann

**Comment by SteffeyDev** [comment]
@Kauffmann9006 If you can run Atem 7.4 or higher, then Issue 1 above was already fixed with the new USK API, and we discovered since then that Issue 2 can be solved by doing a mapping in OSCulator (see #86)

**Comment by JamesFrank2525** [comment]
@SteffeyDev is right. I didn’t have time to properly test issues with USK, so I just put faith in his words that it is solved, but I can confirm that issue 2 is solved.

**Comment by JamesFrank2525** [comment]
Here is my OSCulator file. Keep in mind that is configured for ATEM 1M/E, so the sources are different. Hope it helps!

[ATEM_APC_NEW.zip](https://github.com/danielbuechele/atemOSC/files/2308043/ATEM_APC_NEW.zip)

**Comment by Kauffmann9006** [comment]
Hey guys,

Sorry I didn't react for a while. Was super busy so I didn't have time to test this.

Everything runs smoothly here. Thanks a lot. I've edited everything a but to my liking but it seems to run fine. :-)

I don't really use upstreaming, fancy transitions and audio (hence I have a separate audio mixer plugged in so). The only issues I'm having is the T-Bar slider that when you use the auto function and the slider is in the downward position on the Akai and in the upward position in the software, it suddenly jumps positions when you touch it.

The other thing I'd like to edit is the LED's to switch off when you touch another button (but that's details). Isn't there a way to send a MIDI-message to turn off all other lights. When you touch one? I'll keep you up to date when I find anything.

Thanks a bunch!

Kind regards

**Comment by danielbuechele** [comment]
You can add send multiple MIDI commands from OSCulator when receiving a message. What I do is, when receiving `/atem/program/1` I am sending 8 MIDI messages to turn on LED 1 and turn off LED 2-8.

**Comment by JamesFrank2525** [comment]
That’s a good idea, now we only need to solve the case of using TAKE button so that Program and Preview lights swap ;)

**Comment by jrmilt** [comment]
I’m not in front of my computer right now to attach, but I have an OSCulator file for control using a launchpad MK2 which does not interfere with BMDs ATEM software if you happen to have it open. Might be useful for some people :)

**Comment by jrmilt** [comment]
Also a better way in regards to LED lights is to Demux /atem/program and /atem/preview then have LED on (or change colour in my case) when the value is 1.00 and off at value 0.00. Then you will have a live tally that will reflect what’s on preview and program if you change it on BMD’s software

**Comment by Paradox32** [comment]
How do I find out what OSC commands to use for turning the LED lights on and off? I'm using a Korg NanoKONTROL2 and was going to use the trick to send multiple commands to all lights to get synced feedback on the controller.

**Comment by Paradox32** [comment]
How do you Demux the button press, so that when I try ti tie/untie downstream keyers it will properly toggle instead of setting off when I release the button?

**Comment by SteffeyDev** [comment]
@Kauffmann9006 @Paradox32 did you guys figure out your config spring do you still need help?

**Comment by SteffeyDev** [comment]
Closing, assumed resolved.

**Comment by AlfGent** [comment]
> Un altro modo migliore per quanto riguarda le luci a LED è Demux / atem / program e / atem / preview quindi avere LED acceso (o cambiare colore nel mio caso) quando il valore è 1.00 e spento al valore 0.00. Quindi avrai un conteggio live che rifletterà ciò che è in anteprima e programma se lo cambi sul software BMD

Salve, 

> Un altro modo migliore per quanto riguarda le luci a LED è Demux / atem / program e / atem / preview quindi avere LED acceso (o cambiare colore nel mio caso) quando il valore è 1.00 e spento al valore 0.00. Quindi avrai un conteggio live che rifletterà ciò che è in anteprima e programma se lo cambi sul software BMD

Salve, Sono riuscito a configurare in parte il mio APC mini con Atem Television studio HD, potresti aiutarmi con il comando DEMUX, se puoi postarmi anche uno screenshot dell'istruzione? Grazie

**Comment by ruebyi** [comment]
> You can add send multiple MIDI commands from OSCulator when receiving a message. What I do is, when receiving `/atem/program/1` I am sending 8 MIDI messages to turn on LED 1 and turn off LED 2-8.

Sorry for digging this out,
But cloud you help me with this in Osculator?
Perhaps you‘ve got a demo file?

**Comment by carbon43** [comment]
> How do you Demux the button press, so that when I try ti tie/untie downstream keyers it will properly toggle instead of setting off when I release the button?

I actually just ran into this myself hacking something together last minute using an xbox controller, controllermate, and OSCulator. I guess it'd be solveable with a bit of poking either in controllermate (where Im solid on creating state based vars) or OSCulator (where I barely know anything as I only just downloaded it for this last minute thing), but I didnt get around to it. 

A bit of sample code or a demo would be useful if anyone has something like that to point me towards
