### ISSUE TITLE
ZeroConfig

### ISSUE THREAD

**Issue by kutuz00** [danielbuechele/atemOSC#91]
New version of atemOSC(2.5.3) wont recognize in TouchOSC. Rollover to atemOSC(2.5(1)) to check if its my network. Look like not network issue. Please check. 

P. S. Atem Software control 7.3

**Comment by SteffeyDev** [comment]
Please be more specific.  What does "wont recognize" mean?  What do you see in TouchOSC and what is the indicator of an issue exactly?

**Comment by kutuz00** [comment]
In touchOSC host not showing up. <img src=https://drive.google.com/open?id=1QO1x29uOfg6Rbof2p1OnIlTfNeCov_Rm />
On this img host founded. If i start newer version of atemOSC 2.5.3 Host not showing

**Comment by sneat** [comment]
Won't that be because 2.5.3 only supports Atem version 7.3+?

**Comment by kutuz00** [comment]
This is what I have. Atem version 7.3.

**Comment by sneat** [comment]
Sorry, I meant 7.4 ( see #80 )

**Comment by SteffeyDev** [comment]
@kutuz00 Thank you for identifying this issue and clarifying.  I have identified the problem and issued a fix #93, which will be merged pending review.
