### ISSUE TITLE
Feature Request: choose USK Luma Fill Source

### ISSUE THREAD

**Issue by dappertutto** [danielbuechele/atemOSC#98]
Can this be implemented? As of now, I believe this cannot be changed with atemOSC.

**Comment by SteffeyDev** [comment]
We can certainly try, though I don’t know if any of us have access have a switcher that supports that to test so you may have to verify that it works once added. I’ll mark it as a feature request.

**Comment by dappertutto** [comment]
That would be very much appreciated. I'm thrilled to see action again on this project. I can test on an ATEM Television studio switcher. I can also test on a Prod Studio 4K if that can help

**Comment by dappertutto** [comment]
Dear SteffeyDev, how's it going? Have you or anyone else attempted to implement this? My projects revving up and would love to message that key source and fill source different things, it would really add a lot. Let me know how I can help.

**Comment by SteffeyDev** [comment]
I haven’t started yet, but I should have time next week to try it out. I’ll set a reminder now.

**Comment by SteffeyDev** [comment]
@dappertutto Ok, created #101.  If you have Xcode, you can pull and test.  If not, I'll release soon (I've already tested) and then you can start using.

**Comment by dappertutto** [comment]
oh thats incredible. I don't have experience compiling w/xcode, but I'm happy to wait for the release. Thank you so much!

**Comment by SteffeyDev** [comment]
Closing this, assumed resolved due to lack of response.
