### ISSUE TITLE
ATEMOSC doesn't send commands to my ATEM 4K

### ISSUE THREAD

**Issue by tingkumajique** [danielbuechele/atemOSC#99]
This has left me stumped...

OCUlator's monitoring shows feedback from the ATEM Software Control and that the nanoKONTROL2.
OSCulator's OSC messages is routed to atemOSC but, and atemOSC sees the ATEM Software control.

I also tried touchOSC on my iPad and it detects atemOSC immediately. 

Still no parameter is changing on the Software control when buttons on the nanKONTROL is pressed.

please help!

atemOSC - Version 2.5.3 (1)
ATEM Software Control 7.4

**Comment by SteffeyDev** [comment]
Ok let’s work through this. What do you mean by “atemOSC sees the Atem Software Control”?  If you open the Log panel from the help menu in atemOSC, does it see the message incoming? What message exactly is OSCulator sending that isn’t being updated in Atem Software Control?

Pick one command and trace through, for example
> OSCulator is sending /atem/preview/7 and it is being received by atemOSC (I can see it in the log), but the preview button in Atem Software Control isn’t changing to 7.

**Comment by tingkumajique** [comment]
Hi,
I’m guessing it sees because when I tap on any inputs on the ATEM, Osculator registers incoming commands. Just tapping input one and I have the whole “\atem\program\1” till 8 and other OSCcommands appearing on osculator.

Log panel is blank, which is also another red flag for me.

I did a basic command which is cutting between inputs, and there is no response from the switcher

**Comment by SteffeyDev** [comment]
If atemOSC receives anything, it will print out what it sees; if the log is empty, it is most likely because you are not sending anything to atemOSC to start with. Make sure you are sending to atemOSC on the correct IP address and port, and maybe screenshot your OSCulator configuration and send that along so that we can see if something is configured wrong.

**Comment by tingkumajique** [comment]
![screen shot 2018-06-26 at 10 45 29 pm](https://user-images.githubusercontent.com/40590802/41920260-ed1c57ee-7992-11e8-88bf-9ee08f9edb39.png)

Hi SteffeyDev, I've attached an image of my setup.

**Comment by tingkumajique** [comment]
Hi, am I doing it correctly? What am I not seeing?

Thanks!

**Comment by SteffeyDev** [comment]
Ok, I see a few things it could be:
* Try setting an argument in the router /atem/transition/cut.  You can do this by double-clicking the currently empty arguments field to the right of `/atem/transition/cut`, deleting `<all args>`, typing `1` and then a space, and then using the dropdown that appears to select `float`
* Try specifying the IP address directly: In the target # 2 field, type `osc.udp://127.0.0.1:8000`, and then in the routes section change the route # for `/atem/transition/cut` to 2.
* If you are technically inclined you can install sendosc (https://github.com/yoggy/sendosc) and use the command `./sendosc 127.0.0.1 8000 /atem/transition/cut f 1.0`, and then check the atemOSC log to see if it got it.

**Comment by xtonross** [comment]
It could be the firewall settings from your Mac. Initial press at any of the button on the MIDI controller this pop up message will appear (see image below). You have to select "Allow".
<img width="426" alt="screen shot 2018-06-28 at 7 33 35 pm" src="https://user-images.githubusercontent.com/40080411/42031996-b67b087e-7b0a-11e8-9c7d-3fbe68e3754a.png">

**Comment by tingkumajique** [comment]
Hi,

It's not the firewall as I have it turned off in the system preferences. 
I've tried both options one and 2 and they don't work either...

Attached is a screenshot of what I did... logs are still empty... so strange

![screen shot 2018-06-28 at 11 22 16 pm](https://user-images.githubusercontent.com/40590802/42044192-ee36820a-7b2a-11e8-902d-9ba2edf9a14f.png)

**Comment by SteffeyDev** [comment]
In the OSCulator logs it says it is sending to 192.168.1.25, is that your IP address?  And did you have the chance to check out sendOSC yet?

**Comment by SteffeyDev** [comment]
As this is over a year old, I’m assuming that the issue is resolved.
